# -*- coding: utf-8 -*-
"""segunda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JDHQtyM60WSIdXgALlRc4xbxe-KzUTF
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# CONFIGURACIÓN
# ==========================================

st.set_page_config(
    page_title="Análisis Polinomial Yahoo Finance",
    layout="wide"
)

st.title("📈 Análisis de Soporte, Ruptura y Derivadas Polinomiales")

# ==========================================
# ENTRADAS
# ==========================================

ticker = st.text_input(
    "Clave Yahoo Finance",
    value="BTC-USD"
)

periodo = st.selectbox(
    "Periodo",
    ["5d", "15d", "30d", "60d"],
    index=0
)

intervalo = st.selectbox(
    "Intervalo",
    ["1h", "2h", "4h", "1d"],
    index=0
)

grado_polinomio = st.slider(
    "Grado del Polinomio",
    min_value=2,
    max_value=8,
    value=4
)

# ==========================================
# DESCARGA DE DATOS
# ==========================================

if st.button("Analizar"):

    try:

        datos = yf.download(
            ticker,
            period=periodo,
            interval=intervalo,
            auto_adjust=True
        )

        if len(datos) < 10:
            st.error("No hay suficientes datos.")
            st.stop()

        # ======================================
        # PREPARACIÓN
        # ======================================

        S = datos["Close"]

        Pf2 = pd.DataFrame({
            "Close": S.values
        })

        Pf2["Date"] = np.arange(
            1,
            len(Pf2) + 1
        )

        # ======================================
        # AJUSTE POLINOMIAL
        # ======================================

        coeficientes = np.polyfit(
            Pf2["Date"],
            Pf2["Close"],
            grado_polinomio
        )

        polinomio = np.poly1d(
            coeficientes
        )

        derivada = np.polyder(
            polinomio
        )

        x_fit = np.arange(
            1,
            len(Pf2) + 1
        )

        y_fit = polinomio(
            x_fit
        )

        pendiente = derivada(
            x_fit
        )

        # ======================================
        # ÚLTIMAS PENDIENTES
        # ======================================

        n = min(10, len(pendiente))

        df_resultado = pd.DataFrame({
            "Fecha": datos.index[-n:],
            "Pendiente": pendiente[-n:]
        })

        # ======================================
        # SEÑAL
        # ======================================

        ultima_pendiente = pendiente[-1]

        if ultima_pendiente > 0:
            señal = "🟢 Tendencia Alcista"
        elif ultima_pendiente < 0:
            señal = "🔴 Tendencia Bajista"
        else:
            señal = "🟡 Sin Cambio"

        # ======================================
        # MÉTRICAS
        # ======================================

        c1, c2, c3 = st.columns(3)

        c1.metric(
            "Último Precio",
            round(float(Pf2["Close"].iloc[-1]), 2)
        )

        c2.metric(
            "Última Pendiente",
            round(float(ultima_pendiente), 4)
        )

        c3.metric(
            "Señal",
            señal
        )

        # ======================================
        # TABLA
        # ======================================

        st.subheader("Últimas Pendientes")

        st.dataframe(
            df_resultado,
            use_container_width=True
        )

        # ======================================
        # GRÁFICA PRECIO
        # ======================================

        fig1, ax1 = plt.subplots(
            figsize=(12,6)
        )

        ax1.scatter(
            Pf2["Date"],
            Pf2["Close"],
            s=10,
            label="Precio"
        )

        ax1.scatter(
            Pf2["Date"].iloc[-1],
            Pf2["Close"].iloc[-1],
            s=120,
            label="Último Dato"
        )

        ax1.plot(
            x_fit,
            y_fit,
            linewidth=2,
            label="Ajuste Polinomial"
        )

        ax1.set_title(
            f"{ticker} - Ajuste Polinomial"
        )

        ax1.set_xlabel("Tiempo")
        ax1.set_ylabel("Precio")
        ax1.grid(True)
        ax1.legend()

        st.pyplot(fig1)

        # ======================================
        # GRÁFICA DERIVADA
        # ======================================

        fig2, ax2 = plt.subplots(
            figsize=(12,5)
        )

        ax2.plot(
            datos.index,
            pendiente,
            linewidth=2
        )

        ax2.axhline(
            0,
            linestyle="--"
        )

        ax2.set_title(
            "Derivada del Polinomio"
        )

        ax2.set_ylabel(
            "Pendiente"
        )

        ax2.grid(True)

        st.pyplot(fig2)

    except Exception as e:
        st.error(f"Error: {e}")