# -*- coding: utf-8 -*-
"""segunda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JDHQtyM60WSIdXgALlRc4xbxe-KzUTF
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# CONFIGURACIÓN
# ==========================================

st.set_page_config(
    page_title="Análisis Polinomial",
    layout="wide"
)

st.title("Análisis Polinomial | Antes de invertir")

# ==========================================
# ENTRADAS
# ==========================================

ticker = st.text_input(
    "Clave Yahoo Finance",
    value="BTC-USD"
)

periodo = st.selectbox(
    "Periodo",
    ["5d", "15d", "30d", "60d"],
    index=0
)

intervalo = st.selectbox(
    "Intervalo",
    ["1h", "2h", "4h", "1d"],
    index=0
)

grado_polinomio = st.slider(
    "Grado del Polinomio",
    min_value=2,
    max_value=8,
    value=4
)

# ==========================================
# BOTÓN
# ==========================================

if st.button("Analizar"):

    try:

        # ======================================
        # DESCARGA DE DATOS
        # ======================================

        datos = yf.download(
            ticker,
            period=periodo,
            interval=intervalo,
            auto_adjust=True,
            progress=False
        )

        if datos.empty:
            st.error("No se encontraron datos.")
            st.stop()

        # ======================================
        # CORRECCIÓN MULTIINDEX
        # ======================================

        if isinstance(datos.columns, pd.MultiIndex):
            datos.columns = datos.columns.get_level_values(0)

        # ======================================
        # CIERRES
        # ======================================

        close_prices = datos["Close"].to_numpy().flatten()

        Pf2 = pd.DataFrame({
            "Close": close_prices
        })

        Pf2["Date"] = np.arange(
            1,
            len(Pf2) + 1
        )

        # ======================================
        # AJUSTE POLINOMIAL
        # ======================================

        coeficientes = np.polyfit(
            Pf2["Date"],
            Pf2["Close"],
            grado_polinomio
        )

        polinomio = np.poly1d(
            coeficientes
        )

        # ======================================
        # DERIVADA
        # ======================================

        derivada = np.polyder(
            polinomio
        )

        x_fit = np.arange(
            1,
            len(Pf2) + 1
        )

        y_fit = polinomio(
            x_fit
        )

        pendiente = derivada(
            x_fit
        )

        # ======================================
        # ÚLTIMOS 10 REGISTROS
        # ======================================

        n = min(10, len(pendiente))

        df_resultado = pd.DataFrame({
            "Fecha": datos.index[-n:],
            "Pendiente": pendiente[-n:]
        })

        # ======================================
        # MÉTRICAS
        # ======================================

        ultimo_precio = float(
            Pf2["Close"].iloc[-1]
        )

        ultima_pendiente = float(
            pendiente[-1]
        )

        if ultima_pendiente > 0:
            señal = "🟢 Alcista"
        elif ultima_pendiente < 0:
            señal = "🔴 Bajista"
        else:
            señal = "🟡 Neutral"

        col1, col2, col3 = st.columns(3)

        col1.metric(
            "Último Precio",
            f"{ultimo_precio:,.2f}"
        )

        col2.metric(
            "Última Pendiente",
            f"{ultima_pendiente:.4f}"
        )

        col3.metric(
            "Tendencia",
            señal
        )

        # ======================================
        # TABLA
        # ======================================

        st.subheader("Últimas Pendientes")

        st.dataframe(
            df_resultado,
            use_container_width=True
        )

        # ======================================
        # GRÁFICA PRECIO
        # ======================================

        fig1, ax1 = plt.subplots(
            figsize=(12,6)
        )

        ax1.scatter(
            Pf2["Date"],
            Pf2["Close"],
            s=15,
            label="Precio Real"
        )

        ax1.scatter(
            Pf2["Date"].iloc[-1],
            Pf2["Close"].iloc[-1],
            s=120,
            label="Último Precio"
        )

        ax1.plot(
            x_fit,
            y_fit,
            linewidth=2,
            label="Ajuste Polinomial"
        )

        ax1.set_title(
            f"{ticker} - Ajuste Polinomial"
        )

        ax1.set_xlabel("Tiempo")
        ax1.set_ylabel("Precio")
        ax1.grid(True)
        ax1.legend()

        st.pyplot(fig1)

        # ======================================
        # GRÁFICA DERIVADA
        # ======================================

        fig2, ax2 = plt.subplots(
            figsize=(12,5)
        )

        ax2.plot(
            datos.index,
            pendiente,
            linewidth=2
        )

        ax2.axhline(
            y=0,
            linestyle="--"
        )

        ax2.set_title(
            f"{ticker} - Derivada del Ajuste Polinomial"
        )

        ax2.set_xlabel("Fecha")
        ax2.set_ylabel("Pendiente")

        ax2.grid(True)

        st.pyplot(fig2)

        # ======================================
        # INTERPRETACIÓN
        # ======================================

        st.subheader("Interpretación")

        if ultima_pendiente > 0:
            st.success(
                "La derivada es positiva. El ajuste polinomial muestra una tendencia alcista."
            )

        elif ultima_pendiente < 0:
            st.error(
                "La derivada es negativa. El ajuste polinomial muestra una tendencia bajista."
            )

        else:
            st.warning(
                "La derivada es cercana a cero. No existe una tendencia clara."
            )

    except Exception as e:
        st.error(f"Error: {e}")
